services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.3.5
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - 1G
      - --reserve-memory
      - 0M
      - --node-id
      - "0"
      - --check=false
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:19092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:9092,PLAINTEXT_HOST://localhost:19092
    ports: ["19092:19092", "9092:9092"]


  console:
    image: docker.redpanda.com/redpandadata/console:v2.7.2
    depends_on: [redpanda]
    environment:
      KAFKA_BROKERS: redpanda:9092
    ports: ["8080:8080"]


  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]


  postgres-accounts:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ledgerpw}
      POSTGRES_USER: ${POSTGRES_USER:-ledger}
      POSTGRES_DB: ${POSTGRES_DB_ACCOUNTS:-accounts}
    ports: ["5433:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ledger -d accounts"]
      interval: 5s
      timeout: 5s
      retries: 5


  postgres-ledger:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ledgerpw}
      POSTGRES_USER: ${POSTGRES_USER:-ledger}
      POSTGRES_DB: ${POSTGRES_DB_LEDGER:-ledger}
    ports: ["5434:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ledger -d ledger"]
      interval: 5s
      timeout: 5s
      retries: 5


  postgres-readmodel:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ledgerpw}
      POSTGRES_USER: ${POSTGRES_USER:-ledger}
      POSTGRES_DB: ${POSTGRES_DB_READMODEL:-readmodel}
    ports: ["5435:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ledger -d readmodel"]
      interval: 5s
      timeout: 5s
      retries: 5


  postgres-orchestrator:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ledgerpw}
      POSTGRES_USER: ${POSTGRES_USER:-ledger}
      POSTGRES_DB: ${POSTGRES_DB_ORCHESTRATOR:-orchestrator}
    ports: ["5436:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ledger -d orchestrator"]
      interval: 5s
      timeout: 5s
      retries: 5


  jaeger:
    image: jaegertracing/all-in-one:1.57
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports: ["16686:16686", "4317:4317", "4318:4318"]


  prometheus:
    image: prom/prometheus:v2.54.1
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports: ["9090:9090"]


  grafana:
    image: grafana/grafana:11.1.4
    ports: ["3000:3000"]
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_ADMIN_USER: admin
      GF_INSTALL_PLUGINS: ""
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus

  accounts:
    build:
      context: ..
      dockerfile: services/accounts/Dockerfile
    environment:
      PORT: 7101
      DATABASE_URL: postgres://ledger:${POSTGRES_PASSWORD:-ledgerpw}@postgres-accounts:5432/${POSTGRES_DB_ACCOUNTS:-accounts}?sslmode=disable
    depends_on:
      postgres-accounts:
        condition: service_healthy
    ports: ["7101:7101"]


  ledger-svc:
    build:
      context: ..
      dockerfile: services/ledger/Dockerfile
    environment:
      PORT: 7102
      DATABASE_URL: postgres://ledger:${POSTGRES_PASSWORD:-ledgerpw}@postgres-ledger:5432/${POSTGRES_DB_LEDGER:-ledger}?sslmode=disable
      KAFKA_BROKERS: redpanda:9092
    depends_on:
      postgres-ledger:
        condition: service_healthy
      redpanda:
        condition: service_started
    ports: ["7102:7102"]


  orchestrator:
    build:
      context: ..
      dockerfile: services/posting-orchestrator/Dockerfile
    environment:
      PORT: 7103
      DATABASE_URL: postgres://ledger:${POSTGRES_PASSWORD:-ledgerpw}@postgres-orchestrator:5432/${POSTGRES_DB_ORCHESTRATOR:-orchestrator}?sslmode=disable
      REDIS_URL: redis://redis:6379
      LEDGER_URL: http://ledger-svc:7102
    depends_on:
      postgres-orchestrator:
        condition: service_healthy
      redis:
        condition: service_started
      ledger-svc:
        condition: service_started
    ports: ["7103:7103"]


  read-model:
    build:
      context: ..
      dockerfile: services/read-model/Dockerfile
    environment:
      PORT: 7104
      DATABASE_URL: postgres://ledger:${POSTGRES_PASSWORD:-ledgerpw}@postgres-readmodel:5432/${POSTGRES_DB_READMODEL:-readmodel}?sslmode=disable
      KAFKA_BROKERS: redpanda:9092
    depends_on:
      postgres-readmodel:
        condition: service_healthy
      redpanda:
        condition: service_started
    ports: ["7104:7104"]


  gateway:
    build:
      context: ../services/gateway
      dockerfile: Dockerfile
    environment:
      PORT: 4000
      ACCOUNTS_SERVICE_URL: http://accounts:7101
      ORCHESTRATOR_SERVICE_URL: http://orchestrator:7103
      READMODEL_SERVICE_URL: http://read-model:7104
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
    depends_on:
      accounts:
        condition: service_started
      orchestrator:
        condition: service_started
      read-model:
        condition: service_started
    ports: ["4000:4000"]