// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Balance struct {
	AccountID    pgtype.UUID
	Currency     string
	BalanceMinor int64
	UpdatedAt    pgtype.Timestamptz
}

type EventDedup struct {
	EventID     pgtype.UUID
	ProcessedAt pgtype.Timestamptz
}

type Statement struct {
	ID          int64
	AccountID   pgtype.UUID
	EntryID     pgtype.UUID
	AmountMinor int64
	Side        string
	Ts          pgtype.Timestamptz
}

type Transfer struct {
	ID             pgtype.UUID
	FromAccountID  pgtype.UUID
	ToAccountID    pgtype.UUID
	AmountMinor    int64
	Currency       string
	Status         string
	IdempotencyKey string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
