// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type JournalEntry struct {
	EntryID uuid.UUID
	BatchID uuid.UUID
	Ts      time.Time
	// References the entry_id of the void entry that reversed this entry
	VoidedBy uuid.NullUUID
	// Timestamp when this entry was voided
	VoidedAt sql.NullTime
	// Reason for voiding (e.g., transfer_failed, transfer_rollback)
	VoidReason sql.NullString
}

type JournalLine struct {
	ID          int64
	EntryID     uuid.UUID
	AccountID   uuid.UUID
	AmountMinor int64
	Side        string
}

type Outbox struct {
	ID            uuid.UUID
	AggregateType string
	AggregateID   uuid.UUID
	EventType     string
	Payload       []byte
	Headers       json.RawMessage
	CreatedAt     time.Time
	SentAt        sql.NullTime
}
