// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID        uuid.UUID
	Currency  string
	Status    string
	CreatedAt time.Time
}

type Outbox struct {
	ID            uuid.UUID
	AggregateType string
	AggregateID   uuid.UUID
	EventType     string
	Payload       []byte
	Headers       json.RawMessage
	CreatedAt     time.Time
	SentAt        sql.NullTime
}
