// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getAccount = `-- name: GetAccount :one
SELECT id, currency, status, created_at FROM accounts WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAccount(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
