// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Outbox struct {
	ID            uuid.UUID       `json:"id"`
	AggregateType string          `json:"aggregate_type"`
	AggregateID   uuid.UUID       `json:"aggregate_id"`
	EventType     string          `json:"event_type"`
	Payload       []byte          `json:"payload"`
	Headers       json.RawMessage `json:"headers"`
	CreatedAt     time.Time       `json:"created_at"`
	SentAt        sql.NullTime    `json:"sent_at"`
}

type Transfer struct {
	ID             uuid.UUID      `json:"id"`
	FromAccountID  uuid.UUID      `json:"from_account_id"`
	ToAccountID    uuid.UUID      `json:"to_account_id"`
	AmountMinor    int64          `json:"amount_minor"`
	Currency       string         `json:"currency"`
	IdempotencyKey string         `json:"idempotency_key"`
	Status         string         `json:"status"`
	EntryID        uuid.NullUUID  `json:"entry_id"`
	FailureReason  sql.NullString `json:"failure_reason"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}
